[2021.01.13 18:31:41] I Starting...
[2021.01.13 18:31:42] I Parsing log file finished
[2021.01.14 11:00:47] I Starting...
[2021.01.14 11:00:48] I Parsing log file finished
[2021.01.14 11:03:13] I Starting...
[2021.01.14 11:03:14] I Parsing log file finished
[2021.01.14 11:40:05] I Starting...
[2021.01.14 11:40:05] I Parsing log file finished
[2021.01.14 11:40:32] I Starting...
[2021.01.14 11:40:32] I Report on latest logfile already exist. 
--end--
[2021.01.15 12:12:01] I Start
[2021.01.15 12:12:01] I Trying to open log file:
 "logs\eva-front.custom.access.log"
[2021.01.15 12:12:01] I ok"
[2021.01.15 12:12:14] I Starting to parse log file...
[2021.01.15 12:12:16] I Parsing log file finished.
[2021.01.15 12:12:20] E [Errno 2] No such file or directory: 'reports-examples\\report-target-2021.01.15.1212.html'
Traceback (most recent call last):
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 259, in <module>
    main()
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 252, in main
    with open(latest_log_report_path, 'wb') as report_file:
FileNotFoundError: [Errno 2] No such file or directory: 'reports-examples\\report-target-2021.01.15.1212.html'
[2021.01.15 12:12:24] I Start
[2021.01.15 12:12:24] I Trying to open log file:
 "logs\eva-front.custom.access.log"
[2021.01.15 12:12:24] I ok"
[2021.01.15 12:12:30] I Starting to parse log file...
[2021.01.15 12:12:31] I Parsing log file finished.
[2021.01.15 12:12:35] E [Errno 2] No such file or directory: 'reports-examples\\report-target-2021.01.15.1212.html'
Traceback (most recent call last):
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 258, in <module>
    main()
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 251, in main
    with open(latest_log_report_path, 'wb') as report_file:
FileNotFoundError: [Errno 2] No such file or directory: 'reports-examples\\report-target-2021.01.15.1212.html'
[2021.01.15 12:13:12] I Start
[2021.01.15 12:13:12] I Trying to open log file:
 "logs\eva-front.custom.access.log"
[2021.01.15 12:13:12] I ok"
[2021.01.15 12:13:12] E 'dict_keys' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 260, in <module>
    main()
  File "C:\Users\Front02\workspace\log-analyzer\analyzer.py", line 224, in main
    print(reqs_per_minuts.keys()[:5])
TypeError: 'dict_keys' object is not subscriptable
[2021.01.15 12:14:10] I Start
[2021.01.15 12:14:10] I Trying to open log file:
 "logs\eva-front.custom.access.log"
[2021.01.15 12:14:10] I ok"
[2021.01.15 12:15:34] I Start
[2021.01.15 12:15:34] I Trying to open log file:
 "logs\eva-front.custom.access.log"
[2021.01.15 12:15:34] I ok"
